/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package pharmacymanagementsystem;

import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Date;
import javax.swing.ImageIcon;
/**
 *
 * @author ZBOOK
 */
public class PharmacyManagementSystem extends javax.swing.JFrame {

    private String emailpattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    private String mobileNumberPattern = "^[0-9]*$";
    
    
    /**
     * Creates new form PharmacyManagementSystem
     */
    public PharmacyManagementSystem() {
        initComponents();
        this.setLocationRelativeTo(null);
         search.setBackground(Color.WHITE);
        search.setForeground(new Color(56,78,220));
           update.setBackground(Color.WHITE);
        update.setForeground(new Color(56,78,220));
        jButton1.setBackground(Color.WHITE);
        txtUsername.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        comboUserRole = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dateDOB = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMobileNumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        txtAddress = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(56, 78, 220));
        jLabel1.setText("Update User");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Close Window.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 20, 20));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 850, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(56, 78, 220));
        jLabel2.setText(" User Name :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 120, 20));

        txtUsername.setText(" ");
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 300, 30));

        search.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        search.setForeground(new java.awt.Color(56, 78, 220));
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image2/search.png"))); // NOI18N
        search.setText("Search");
        search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchMouseExited(evt);
            }
        });
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 120, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(56, 78, 220));
        jLabel3.setText("User Role");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        comboUserRole.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        comboUserRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " Admin", "Pharmacist" }));
        getContentPane().add(comboUserRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 204, 300, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(56, 78, 220));
        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 252, 50, -1));

        txtName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtName.setText(" ");
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 280, 300, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(56, 78, 220));
        jLabel5.setText("DOB(Date Of Birth)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        dateDOB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(dateDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 300, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(56, 78, 220));
        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 80, -1));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtEmail.setText(" ");
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 204, 300, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(56, 78, 220));
        jLabel7.setText("Mobile Number");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 252, -1, -1));

        txtMobileNumber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtMobileNumber.setText(" ");
        getContentPane().add(txtMobileNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 280, 300, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(56, 78, 220));
        jLabel8.setText("Address");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, -1, -1));

        update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        update.setForeground(new java.awt.Color(56, 78, 220));
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image2/save.png"))); // NOI18N
        update.setText("Update");
        update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, -1, 40));

        txtAddress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtAddress.setText(" ");
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 368, 300, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image2/back.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        int checkUserExist=0;
        String username = txtUsername.getText();
        if(username.equals("")){
        JOptionPane.showMessageDialog(null,"Username field is required !");
        }else{
                SimpleDateFormat dformat = new SimpleDateFormat("dd-MM-yyyy");
                try{
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy", "abdo","abdo1234");
                    Statement st = con.createStatement();
                    ResultSet rs =st.executeQuery("select *from appuser where username = '"+username+"'");
                    while(rs.next()){
                    txtUsername.setEditable(false);
                    checkUserExist = 1;
                    txtName.setText(rs.getString( "name"));System.out.print(rs.getString("name"));
                    txtMobileNumber.setText(rs.getString("mobileNumber"));
                    txtEmail.setText(rs.getString("email"));
                    txtAddress.setText(rs.getString("address"));
               String dob = rs.getString("dob");
                      if(dob!=""){
                      try{
                           dateDOB.setDate(dformat.parse(dob));
                         }
                      catch(Exception e){}
                      }
                     if(rs.getString("userRole").equals("Admin")){
                       comboUserRole.removeAllItems();
                       comboUserRole.addItem("Admin");
                       comboUserRole.addItem("Pharmacist");
                     }
                  else{
                      comboUserRole.removeAllItems();
                      comboUserRole.addItem("Pharmacist");
                      comboUserRole.addItem("Admin");
                     }  
               }
     
     
                }
                catch(Exception e){
                      JOptionPane.showMessageDialog(null,e);
                }
                if(checkUserExist == 0){
                JOptionPane.showMessageDialog(null, "Username does not exist.");
                }
        }
    }//GEN-LAST:event_searchActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        
        String userRole = (String) comboUserRole.getSelectedItem();
        String name = txtName.getText();
        SimpleDateFormat dformat= new SimpleDateFormat("dd-MM-yyyy");
        Date date = dateDOB.getDate();
        String dob ="";
        if(date != null){
        dob = dformat.format(dateDOB.getDate());
        }
        String mobileNumber= txtMobileNumber.getText();
        String email = txtEmail.getText();
        String username = txtUsername.getText();
        String address =txtAddress.getText();
        
        if(name.equals("")){
        JOptionPane.showMessageDialog(null, "Name field is required.");
        }else if (dob.equals("")){
         JOptionPane.showMessageDialog(null, "Date of Birth field is required.");
        }else if(mobileNumber.equals("")){
         JOptionPane.showMessageDialog(null, "Mobile Number field is required.");
        }else if (!mobileNumber.matches(mobileNumberPattern)/*||mobileNumber.length() !=10*/){
         JOptionPane.showMessageDialog(null, "Mobile Number field is Invalid.");
        }else if (email.equals("")){
         JOptionPane.showMessageDialog(null, "Email field is required.");
        }else if(!email.matches(emailpattern)){
         JOptionPane.showMessageDialog(null, "Email field is Invalid.");
        }else if(username.equals("")){
         JOptionPane.showMessageDialog(null, "Username field is required.");
        }else if(address.equals("")){
        JOptionPane.showMessageDialog(null, "Address field is required.");
        }else{
        try{
     Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy", "abdo","abdo1234");
     PreparedStatement ps = con.prepareStatement("Update appUser set userRole=?, name=?,dob=?,mobileNumber=?,email=?,address=? where username=?");
     ps.setString(1,userRole);
     ps.setString(2,name);
     ps.setString(3,dob);
     ps.setString(4,mobileNumber);
     ps.setString(5,email);
     ps.setString(6, address);
     ps.setString(7,username);
     ps.executeUpdate();
     JOptionPane.showMessageDialog(null, "User Updated Successfully ");
     setVisible(false);
     new PharmacyManagementSystem  ().setVisible(true);
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null,  e);
        }
        }  
    }//GEN-LAST:event_updateActionPerformed

    private void searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseEntered
        // TODO add your handling code here:
         search.setBackground(new Color(56,78,220));
        search.setForeground(Color.WHITE);
    // Set icon for the button
    ImageIcon icon = new ImageIcon("src\\image2\\search.png");
    search.setIcon(icon);

    }//GEN-LAST:event_searchMouseEntered

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
        // TODO add your handling code here:
         update.setBackground(new Color(56,78,220));
        update.setForeground(Color.WHITE);
    // Set icon for the button
    ImageIcon icon = new ImageIcon("src\\image2\\save.png");
    update.setIcon(icon);
    }//GEN-LAST:event_updateMouseEntered

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
        // TODO add your handling code here:
           update.setBackground(Color.WHITE);
        update.setForeground(new Color(56,78,220));
    // Set icon for the button
    ImageIcon icon = new ImageIcon("src\\image2\\save.png");
    update.setIcon(icon);
    }//GEN-LAST:event_updateMouseExited

    private void searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseExited
        // TODO add your handling code here:
         search.setBackground(Color.WHITE);
        search.setForeground(new Color(56,78,220));
    // Set icon for the button
    ImageIcon icon = new ImageIcon("src\\image2\\search.png");
    search.setIcon(icon);
    }//GEN-LAST:event_searchMouseExited

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PharmacyManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PharmacyManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PharmacyManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PharmacyManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PharmacyManagementSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboUserRole;
    private com.toedter.calendar.JDateChooser dateDOB;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton search;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMobileNumber;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

 
}
       
